language: cpp
dist: focal
matrix:
    include:
    - env: TARGET=MVC
addons:
 apt:
  packages:
  - doxygen
script:
 - cmake .
 - cmake --build .
 - cmake --build . --target test
 - cmake --build . --target package
 - doxygen Doxyfile