language: cpp
dist: focal
matrix:
    include:
    - env: TARGET=MVC
addons:
 apt:
  packages:
  - doxygen
before_script:
 - cd ../doxygen
 - sudo apt install graphviz -y
 - sudo apt install ./doxygen_1.8.19_amd64.deb
 - doxygen --version
 - cd ..
script:
 - cmake .
 - cmake --build .
 - cmake --build . --target test
 - cmake --build . --target package
 - doxygen Doxyfile