language: cpp
dist: focal
matrix:
    include:
    - env: TARGET=MVC
addons:
 apt:
  packages:
  - doxygen
install:
  - sudo apt-get install -y doxygen graphviz
script:
 - cmake .
 - cmake --build .
 - cmake --build . --target test
 - cmake --build . --target package
 - doxygen Doxyfile
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: ./Documentation/html
    keep_history: true
    on:
      branch: master